name = "pokepackdle"
main = "worker.js"
compatibility_date = "2025-01-01"

# Usernames that are admins on the server (comma separated). Register these accounts first, before sharing the game.
[vars]
ADMINS = "CdukingGD"

[[d1_databases]]
binding = "DB"
database_name = "pokepackdle"
database_id = "cc0b1643-0fb1-434b-8a7d-96dc6be88208"
